Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2018-12, with the labels that each got.

#589 Fixes #563, fixes #562 -- Voeg ontbrekende headers toe aan API spec
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: bug, verbetering

#635 Added CI badges for reference implementations &…
  README.md
Labels: ops

#476 Functionele documentatie 'zaken' API
  docs/_content/overige/functioneel/zaken_api.md
Labels: Documentatie
