Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2018-08, with the labels that each got.

#207 ‘feature/rotterdam samenloop’
  3drotterdam.png
  architectuurschetsrotterdam.png
  datenwat.png
  docs/processen/rotterdam-samenloop.md
  informatieburgers.png
Labels: WIP, architectuur

#213 Dimpact MOR review JG verwerkt
  docs/processen/Dimpact-MOR.md
  docs/processen/bestanden/Dimpact/apis-componenten-dimpact.png
  docs/processen/bestanden/Dimpact/apis-componenten-generiek.png
  docs/processen/bestanden/Dimpact/apis-componenten.png
  docs/processen/bestanden/Dimpact/architectuurschets-dimpact-mor.archimate
  docs/processen/bestanden/Dimpact/mor-proces.png
Labels: WIP

#288 Fixes #169 -- MOR voor Dimpact
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: MOR, verbetering

#333 Creatie ontwerpkeuzes-infomodellen.md 2e poging
  docs/content/developers/ontwerpkeuzes-informatiemodellen.md
Labels: hulp nodig
