Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2018-10, with the labels that each got.

#439 Create sjabloon.md
  docs/content/functioneel/sjabloon.md
Labels: Review Pull-request

#430 Aanzet functionele documentatie
  docs/content/functioneel/zaken_api.md
Labels: Review Pull-request

#329 Gerelateerde objecten zonder eigen resource / Groepattributen
  docs/content/developers/design-keuzes.md
Labels: Prio H, Review Pull-request

#455 Update als-----wil-ik----.md
  .github/ISSUE_TEMPLATE/als-----wil-ik----.md
Labels: Review Pull-request

#445 Architectuurschets samenloopdetectie sociaal domein (Rotterdam)
  docs/processen/bestanden/rotterdam/US65-arch-1.png
  docs/processen/bestanden/rotterdam/US65-arch-2.png
  docs/processen/bestanden/rotterdam/US65-arch-3.png
  docs/processen/bestanden/rotterdam/architectuurschetsrotterdam.png
  docs/processen/rotterdam-samenloop sociaal domein.md
Labels: Review Pull-request, architectuur

#407 Create rotterdam-samenloop-Fysiek Domein.md
  docs/processen/rotterdam-samenloop-Fysiek Domein.md
Labels: Review Pull-request

#470 Create 20181004-demo-sprint-4.md
  20181004-demo-sprint-4.md
Labels: Review Pull-request

#471 Update bijeenkomsten.md
  docs/content/community/bijeenkomsten.md
Labels: Review Pull-request

#351 Zaak afsluiten design keuze toegevoegd
  docs/content/developers/design-keuzes.md
Labels: Prio H, Verhef tot ontwerp keuze

#489 Fixes #161 Implementeer Zaak afsluiten volgens design keuze.
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: Review Pull-request, blok

#482 Update 20181004-demo-sprint-4.md
  20181004-demo-sprint-4.md
  docs/content/community/bijeenkomsten.md
  docs/content/community/bijeenkomsten/20181004-demo-sprint-4.md
Labels: Communicatie

#483 Update 20180827-demo-sprint-3.md
  docs/content/community/bijeenkomsten/20180827-demo-sprint-3.md
Labels: Communicatie
