Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2018-09, with the labels that each got.

#343 Ref #130 -- Documenteer meerdere validatiefouten responses
  docs/content/developers/design-keuzes.md
Labels: DSO, Review Pull-request

#339 Voeg template voor PR toe
  .github/PULL_REQUEST_TEMPLATE/spec-wijziging.md
Labels: Review Pull-request

#400 Afwijkingen van DSO toestaan mits gedocumenteerd
  .github/ISSUE_TEMPLATE/als-----wil-ik----.md
Labels: Review Pull-request

#360 Ref. #130 -- documenteer validaties & fout responses (in WIP-standaard)
  README.md
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
  standaard.md
Labels: Review Pull-request, beheer
