Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-03, with the labels that each got.

#809 Fixes #797 -- ontbrekende scopes bij DELETE operaties in API specs
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
Labels: EPIC Archiefbeheer, bug

#823 Fixes #820 -- include URLs to EUPL-1.2 license in API specs
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: Documentatie

#828 20190228-demo-spint-9.md
  docs/_content/community/bijeenkomsten/20190227-demo-sprint-9.md
Labels: Communicatie

#830 Added pagination to /zaken and /zaken/_zoek endpoints
  api-specificatie/zrc/openapi.yaml
Labels: DEV

#833 Fixes #831 -- increase URL lengths
  api-specificatie/zrc/openapi.yaml
  docs/Dockerfile
  docs/Gemfile.lock
Labels: bug

#825 Fixes #609 -- documenteer afleiding InformatieObject.vertrouwelijkheidaanduiding
  api-specificatie/ztc/openapi.yaml
  docs/_content/standaard/standaard.md
Labels: Documentatie, Documenten

#850 Update bijdragen.md
  docs/_content/community/bijdragen.md
Labels: Communicatie

#851 Documentatie notificaties
  api-specificatie/nc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  docs/_content/ontwikkelaars/notificeren.md
  docs/_content/standaard/apis/nc.md
  docs/_content/standaard/standaard.md
Labels: EPIC Notificatie
