Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-05, with the labels that each got.

#944 Update als-----wil-ik----.md
  .github/ISSUE_TEMPLATE/als-----wil-ik----.md
Labels: Communicatie

#962 :memo: Processen verplaatst naar archief buiten documentatie.
  docs/archief/processen/Delft AVG.md
  docs/archief/processen/Dimpact-MOR.md
  docs/archief/processen/amsterdam-water.md
  docs/archief/processen/bestanden/Delft-Inzageverzoek/Architectuurschets Inzageverzoek AVG.png
  docs/archief/processen/bestanden/Delft-Inzageverzoek/Class Diagram AVG Inzageverzoek.png
  docs/archief/processen/bestanden/Delft-Inzageverzoek/Proces view Inzageverzoek AVG v2.png
  docs/archief/processen/bestanden/Dimpact/apis-componenten-dimpact.png
  docs/archief/processen/bestanden/Dimpact/apis-componenten-generiek.png
  docs/archief/processen/bestanden/Dimpact/architectuurschets-dimpact-mor.archimate
  docs/archief/processen/bestanden/Dimpact/mor-proces.png
  docs/archief/processen/bestanden/Utrecht/DRC-DMS.PNG
  docs/archief/processen/bestanden/Utrecht/Userstorybeschrijvingen.md
  docs/archief/processen/bestanden/amsterdam/GEMMA_Mapping.png
  docs/archief/processen/bestanden/amsterdam/Overview_proc_sys_obj_signalen.png
  docs/archief/processen/bestanden/amsterdam/Overview_proc_sys_signalen.png
  docs/archief/processen/bestanden/amsterdam/Procesflow.png
  docs/archief/processen/bestanden/amsterdam/Signalen_architectuur_globaal.png
  docs/archief/processen/bestanden/rotterdam/3drotterdam.png
  docs/archief/processen/bestanden/rotterdam/US65-arch-1.png
  docs/archief/processen/bestanden/rotterdam/US65-arch-2.png
  docs/archief/processen/bestanden/rotterdam/US65-arch-3.png
  docs/archief/processen/bestanden/rotterdam/datenwat.png
  docs/archief/processen/bestanden/rotterdam/informatieburgers.png
  docs/archief/processen/index.md
  docs/archief/processen/rotterdam-samenloop sociaal domein.md
  docs/archief/processen/rotterdam-samenloop-Fysiek Domein.md
Labels: Documentatie

#963 Update 20180802-demo-sprint-2.md
  docs/_content/community/bijeenkomsten/20180802-demo-sprint-2.md
Labels: Communicatie

#958 Eerste versie van de audit trail API
  docs/_content/ontwikkelaars/algemeen/audit-trail.md
Labels: Documentatie, EPIC Audittrail en Versiebeheer

#964 Update ontwerpkeuzes-informatiemodellen.md
  docs/_content/overige/functioneel/ontwerpkeuzes-informatiemodellen.md
Labels: Communicatie

#972 Update guides.md
  docs/_content/ontwikkelaars/guides.md
Labels: Documentatie

#961 Update productvisie.md
  docs/_content/introductie/productvisie.md
Labels: Communicatie

#978 Update 20190425-demo-sprint-11.md
  docs/_content/community/bijeenkomsten/20190425-demo-sprint-11.md
Labels: Communicatie

#966 Update bijdragen.md
  docs/_content/community/bijdragen.md
Labels: Communicatie

#987 Update README.md
  README.md
Labels: Communicatie

#988 Update index.md
  docs/index.md
Labels: Communicatie

#993 Aanscherping audit trail spec
  docs/_content/ontwikkelaars/algemeen/audit-trail.md
Labels: Documentatie

#998 Update all API specs after updating to new auth format
  api-specificatie/ac/openapi.yaml
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/nrc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: EPIC Autorisatie

#1002 Delete ontwerpkeuzes-informatiemodellen.md
  docs/_content/overige/functioneel/ontwerpkeuzes-informatiemodellen.md
Labels: Communicatie, Informatiemodel

#1003 Nieuw linkje in architectuur
  docs/_content/architectuur/zds_zgw.md
Labels: Communicatie

#1005 Vervanging roodmap (duidelijker leesbaar)
  docs/_content/introductie/_assets/roadmap.png
Labels: Communicatie

#1015 Update bronnen.md
  docs/_content/introductie/bronnen.md
Labels: Communicatie

#1014 Update zds_zgw.md
  docs/_content/architectuur/zds_zgw.md
Labels: Communicatie

#1000 Fixes #722 -- Add audittrail
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
Labels: EPIC Audittrail en Versiebeheer

#1019 Update zds_zgw.md
  docs/_content/architectuur/zds_zgw.md
Labels: Communicatie

#1024 Update 20190425-demo-sprint-11.md
  docs/_content/community/bijeenkomsten/20190425-demo-sprint-11.md
Labels: Communicatie

#1029 Update 20190425-demo-sprint-11.md
  docs/_content/community/bijeenkomsten/20190425-demo-sprint-11.md
Labels: Communicatie

#1040 :pencil2: Typo
  .github/ISSUE_TEMPLATE/als-----wil-ik----.md
Labels: Communicatie

#1043 Update index.md
  docs/_content/standaard/index.md
Labels: Communicatie

#1030 Create Ontwerpkeuzes.md
  docs/_content/architectuur/ontwerpkeuzes.md
  docs/_content/architectuur/ontwikkelstraat.md
Labels: Documentatie

#1036 Add files via upload
  docs/_content/introductie/Definition-of-done.md
  docs/_content/introductie/_assets/dod.png
Labels: Communicatie

#984 Update zds-vs-zgw.md
  docs/_content/overige/technisch/zds-vs-zgw.md
Labels: Documentatie
