Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-07, with the labels that each got.

#1140 Simplified one-time setup
  docs/_content/ontwikkelaars/tutorials/eenmalige-setup.md
  infra/docker-compose.yml
Labels: EPIC API-lab april/juni/juli

#1143 Update API specs
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: EPIC Nodig voor Release Candidate (Sprint 13 en14)

#1142 Document that ZRC@0.18+ needs DRC@0.15+
  docs/_content/ontwikkelaars/api-compatibiliteit.md
Labels: Documentatie

#1158 Finalize inway config
  infra/ingress.yml
  infra/inway/inway.yml
Labels: OPS

#1166 Infra refactor
  .gitignore
  infra/README.md
  infra/ansible/ansible.cfg
  infra/ansible/deploy_secrets.yml
  infra/ansible/hosts
  infra/ansible/vars.yml
  infra/k8s/ac/secrets.yml
  infra/k8s/ac/web.yml
  infra/k8s/brc/secrets.yml
  infra/k8s/brc/web.yml
  infra/k8s/database/postgis.yml
  infra/k8s/database/secrets.yml
  infra/k8s/demo/config.yml
  infra/k8s/demo/nginx.yml
  infra/k8s/demo/redis.yml
  infra/k8s/demo/volumes.yml
  infra/k8s/demo/web.yml
  infra/k8s/deploy/rbac.yml
  infra/k8s/deploy/secrets.yml
  infra/k8s/deploy/web.yml
  infra/k8s/docs/web.yml
  infra/k8s/drc/nginx.yml
  infra/k8s/drc/secrets.yml
  infra/k8s/drc/volumes.yml
  infra/k8s/drc/web.yml
  infra/k8s/ingress.yml
  infra/k8s/inway/inway.yml
  infra/k8s/inway/secrets.yml
  infra/k8s/nrc/celery.yml
  infra/k8s/nrc/rabbitmq.yml
  infra/k8s/nrc/secrets.yml
  infra/k8s/nrc/web.yml
  infra/k8s/old_domain/ingress.yml
  infra/k8s/old_domain/nginx.yml
  infra/k8s/tokens/secrets.yml
  infra/k8s/tokens/web.yml
  infra/k8s/vrl/secrets.yml
  infra/k8s/vrl/web.yml
  infra/k8s/zrc/secrets.yml
  infra/k8s/zrc/web.yml
  infra/k8s/ztc/secrets.yml
  infra/k8s/ztc/web.yml
  infra/nrc/secrets.yml
  infra/requirements.in
  infra/requirements.txt
Labels: OPS

#1185 Update API specs ZRC, DRC, ZTC & BRC
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: EPIC Nodig voor Release Candidate (Sprint 13 en14)

#1193 Update faq.md
  docs/_content/overige/faq.md
Labels: Documentatie

#1203 Update index.md
  docs/index.md
Labels: bug

#1217 Script celery worker w/ availability check
  infra/k8s/nrc/celery.yml
Labels: EPIC Notificatie, OPS
