Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-04, with the labels that each got.

#872 Create 20190328-demo-sprint-1-.md
  docs/_content/community/bijeenkomsten/20190328-demo-sprint-10.md
Labels: Communicatie

#867 Update bijdragen.md
  docs/_content/community/bijdragen.md
Labels: Communicatie

#896 Update bijdragen.md
  docs/_content/community/bijdragen.md
Labels: Communicatie

#902 Update API-spec NRC with flattened filters
  api-specificatie/nc/openapi.yaml
  docs/_content/ontwikkelaars/notificeren.md
Labels: EPIC API-lab april/juni/juli, EPIC Notificatie

#772 Aanscherping berekening archiefactietermijn en...
  docs/_content/ontwikkelaars/algemeen/archiveren.md
Labels: EPIC Archiefbeheer

#915 Add API-lab slides
  docs/_content/ontwikkelaars/tutorials/archiveren.md
  docs/_content/ontwikkelaars/tutorials/archiveren.pptx
  docs/_content/ontwikkelaars/tutorials/autorisatie.pptx
  docs/_content/ontwikkelaars/tutorials/eenmalige-setup.md
  docs/_content/ontwikkelaars/tutorials/notificeren.md
  docs/_content/ontwikkelaars/tutorials/notificeren.pptx
Labels: EPIC API-lab april/juni/juli

#929 Fixes #928 -- added filter parameters to DRC
  api-specificatie/drc/openapi.yaml
Labels: Convenience, Documenten, Issue uit API-lab

#935 Update NRC API spec & voeg consumer API spec toe
  api-specificatie/nrc/consumer-api/openapi.yaml
  api-specificatie/nrc/openapi.yaml
  docs/_content/standaard/apis/nrc.md
  docs/_content/standaard/standaard.md
Labels: Documentatie, EPIC Notificatie

#941 Fixes #442 -- documenteer afsluiten/heropenen zaak
  api-specificatie/zrc/openapi.yaml
  docs/_content/standaard/standaard.md
Labels: EPIC Archiefbeheer

#815 Update standaard.md
  docs/_content/standaard/standaard.md
Labels: Documentatie, EPIC Archiefbeheer, Validatie

#946 Update index.md
  docs/_content/community/index.md
Labels: Communicatie

#947 Update index.md
  docs/_content/community/index.md
Labels: Communicatie

#953 locatie voor 20 juni ook toegevoegd
  docs/_content/community/index.md
Labels: Communicatie

#948 Update bijdragen.md
  docs/_content/community/bijdragen.md
Labels: Communicatie, Documentatie
