Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-11, with the labels that each got.

#1355 Update versies-en-migraties.md
  docs/_content/themas/achtergronddocumentatie/versies-en-migraties.md
Labels: Documentatie

#1438 Update ZTC API spec - include deelzaaktypen
  api-specificatie/ztc/1.0.x/openapi.yaml
Labels: Documentatie

#1423 Visie op Verzoeken (API)
  docs/_content/standaard/verzoeken/index.md
Labels: EPIC Verzoeken

#1454 Updates to 1.0.x versions of ZTC & BRC
  api-specificatie/brc/1.0.x/openapi.yaml
  api-specificatie/ztc/1.0.x/openapi.yaml
Labels: Documentatie

#1483 Bump transitive mem dependency to fix security report
  deploy-bot/package-lock.json
Labels: OPS

#1486 Fixes #1480 -- rename contactmomenten -> klantinteracties API
  README.md
  api-specificatie/kic/1.0.x/openapi.yaml
  docs/_content/standaard/contactmomenten/index.md
  docs/_content/standaard/index.md
  docs/_content/standaard/klantinteracties/Contactmomenten API 1.0.0.png
  docs/_content/standaard/klantinteracties/index.md
  infra/ansible/vars/secrets-test.yml
  infra/ansible/vars/secrets.yml
  infra/ansible/vars/stable.yml
  infra/ansible/vars/test.yml
  infra/k8s/cmc/secrets.yml
  infra/k8s/cmc/web.yml
  infra/k8s/ingress.yml
  infra/k8s/inway/inway.yml
Labels: Documentatie

#1447 Badge van het API Test Platform
  README.md
Labels: API Test Platform

#1489 :pencil: Removed reference to ZDS 2.0
  README.md
Labels: Documentatie

#1477 Add missing validation documentation
  docs/_content/standaard/besluiten/index.md
  docs/_content/standaard/zaken/index.md
Labels: Documentatie
