Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-09, with the labels that each got.

#1282 Add demo redirect
  infra/k8s/old_domain/nginx.yml
Labels: OPS

#1235 Update API specs n.a.v. RC1 bevindingen
  api-specificatie/ac/openapi.yaml
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/nrc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
  docs/_content/standaard/besluiten/index.md
Labels: Beheer

#1299 Fixes #1266 -- Added new business rule voor Autorisaties in AC
  docs/_content/standaard/autorisaties/index.md
Labels: Validatie
