Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-10, with the labels that each got.

#1305 Bump versions to rc2
  api-specificatie/ac/openapi.yaml
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/nrc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
  infra/ansible/vars/stable.yml
  infra/docker-compose.yml
  infra/k8s/drc/web.yml
  infra/k8s/nrc/celery.yml
  infra/k8s/nrc/web.yml
  infra/k8s/zrc/web.yml
  infra/k8s/ztc/web.yml
Labels: OPS

#1362 Fixes #1287 -- documenteer testomgevingen
  docs/_content/ontwikkelaars/index.md
Labels: Documentatie

#1332 Added ZTC concept explanation to standaard
  docs/_content/standaard/catalogi/index.md
Labels: Documentatie

#1372 Enable zaken-auth.test.vng.cloud
  infra/ansible/vars/test.yml
  infra/k8s/demo/web.yml
Labels: OPS

#1376 Update index.md
  docs/index.md
Labels: Documentatie

#1369 upload large files doc
  docs/_content/ontwikkelaars/handleidingen-en-tutorials/_assets/postman_multipart.png
  docs/_content/ontwikkelaars/handleidingen-en-tutorials/large-files.md
  docs/_content/ontwikkelaars/index.md
Labels: 1.1, Documentatie

#1377 Fixes #1365 -- document HTTP caching in catalogi API
  api-specificatie/ztc/1.0.x/openapi.yaml
  api-specificatie/ztc/1.1.x/openapi.yaml
  docs/_content/standaard/catalogi/index.md
Labels: 1.1, Documentatie

#1378 Refs #1078 -- document large file uploads mechanism
  api-specificatie/drc/1.1.x/openapi.yaml
Labels: 1.1, Documentatie
