Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-01, with the labels that each got.

#661 Fixes #634 -- rename catalogus/zaaktype relaties
  api-specificatie/ztc/openapi.yaml
Labels: verbetering

#697 Verschil en overeenkomsten tussen ZDS en ZGW samengevat.
  docs/_content/overige/technisch/zds-vs-zgw.md
Labels: Documentatie

#707 Create besluiten_api.md
  docs/_content/overige/functioneel/besluiten_api.md
Labels: Besluit, Documentatie

#451 Functionele documentatie 'zaaktypen' API
  docs/_content/overige/functioneel/zaaktypen_api.md
Labels: Documentatie

#457 Functionele documentatie 'informatieobjecten' API
  docs/content/functioneel/informatieobjecten_api.md
Labels: Documentatie
