Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-02, with the labels that each got.

#755 Rename docs/content/functioneel/informatieobjecten_api.md to docs/_co…
  docs/_content/overige/functioneel/informatieobjecten_api.md
Labels: Documentatie

#759 Fixes #620 -- improve API-documentation
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
Labels: Documentatie, Review Pull-request

#670 Inzageverzoek AVG upload class diagram
  docs/_content/overige/processen/Delft AVG.md
  docs/_content/overige/processen/bestanden/Delft-Inzageverzoek/Class Diagram AVG Inzageverzoek.png
Labels: AVG

#758 [WIP] Eerste insteek van archiveren
  docs/_content/ontwikkelaars/algemeen/archiveren.md
Labels: Documentatie, EPIC Archiefbeheer, WIP

#764 [WIP] Eerste insteek van notificaties
  docs/_content/ontwikkelaars/algemeen/notificaties.md
Labels: EPIC Notificatie (Sprint 10)

#794 Update bug.md
  .github/ISSUE_TEMPLATE/bug.md
Labels: Improvement

#793 Fixes #344 -- voeg resultaattype toe
  api-specificatie/ztc/openapi.yaml
  docs/_content/standaard/standaard.md
Labels: EPIC Archiefbeheer, ZTC
