Repository VNG-Realisatie/gemma-zaken, pull requests merged in 2019-06, with the labels that each got.

#1006 Documentatie branch cm
  docs/.gitignore
  docs/_content/ontwikkelaars/aan-de-slag.md
  docs/_content/ontwikkelaars/index.md
  docs/_content/overige/begrippenlijst.md
  docs/_content/overige/bronnen.md
  docs/_content/overige/faq.md
  docs/_content/overige/samenwerking.md
  docs/_content/productvisie/index.md
  docs/_data/navigation.yml
  docs/index.md
Labels: Communicatie

#1047 Update index.md
  docs/_assets/img/slack.png
  docs/index.md
Labels: Communicatie

#1050 Rename deelnemende_partijen.md to docs/_content/scrumteam.md
  deelnemende_partijen.md
  docs/_content/scrumteam.md
Labels: Communicatie

#1059 Update 20190523-demo-sprint-12.md
  docs/_content/community/bijeenkomsten/20190523-demo-sprint-12.md
Labels: Communicatie

#1054 API specificatie updates
  api-specificatie/ac/openapi.yaml
  api-specificatie/brc/openapi.yaml
  api-specificatie/drc/openapi.yaml
  api-specificatie/nrc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
  api-specificatie/ztc/openapi.yaml
Labels: Documentatie, EPIC Nodig voor Release Candidate (Sprint 13 en14)

#1052 Update begrippenlijst.md
  docs/_content/overige/begrippenlijst.md
Labels: Communicatie

#1060 Autorisatie & audittrail in standaard.md
  docs/_content/standaard/standaard.md
Labels: Documentatie

#1068 dode link fix
  docs/index.md
Labels: Documentatie

#1069 Rename docs/_content/scrumteam.md to docs/_content/community/scrumtea…
  docs/_content/community/scrumteam.md
  docs/index.md
Labels: Documentatie

#1076 Update begrippenlijst.md
  docs/_content/overige/begrippenlijst.md
Labels: Documentatie

#1079 Update faq.md
  docs/_content/overige/faq.md
Labels: Documentatie

#1075 Add files via upload
  docs/_content/standaard/apis.png
  docs/_content/standaard/index.md
Labels: Documentatie

#1088 Update API-specs ZRC & DRC
  api-specificatie/drc/openapi.yaml
  api-specificatie/zrc/openapi.yaml
Labels: EPIC Nodig voor Release Candidate (Sprint 13 en14)

#1097 Update DRC & ZRC API spec
  api-specificatie/zrc/openapi.yaml
Labels: EPIC Nodig voor Release Candidate (Sprint 13 en14)

#1112 Update scrumteam.md
  docs/_content/community/scrumteam.md
Labels: Documentatie

#1109 Update README.md
  README.md
Labels: Documentatie

#1115 Update 20190620-demo-sprint-13.md
  docs/_content/community/bijeenkomsten/20190620-demo-sprint-13.md
Labels: Communicatie, Documentatie

#1117 Update scrumteam.md
  docs/_content/community/scrumteam.md
Labels: Documentatie

#1129 Update scrumteam.md
  docs/_content/community/scrumteam.md
Labels: Documentatie
